## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

# Import pandas and read the charity_data.csv from the provided cloud URL.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns=['EIN', 'NAME'])

In [3]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# View value counts for APPLICATION_TYPE
application_df['APPLICATION_TYPE'].value_counts()

# Identify application types to replace if they occur fewer than 500 times
application_type_counts = application_df['APPLICATION_TYPE'].value_counts()
application_types_to_replace = application_type_counts[application_type_counts < 500].index

# Replace rare application types with "Other"
application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(application_types_to_replace, 'Other')

In [5]:

# View value counts for APPLICATION_TYPE
application_df['APPLICATION_TYPE'].value_counts()

# Identify application types to replace if they occur fewer than 500 times
application_type_counts = application_df['APPLICATION_TYPE'].value_counts()
application_types_to_replace = application_type_counts[application_type_counts < 500].index

# Replace rare application types with "Other"
application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(application_types_to_replace, 'Other')

# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(application_type_counts[application_type_counts < 500].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app, "Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
classification_counts = application_df['CLASSIFICATION'].value_counts()
classification_types_to_replace = classification_counts[classification_counts < 1000].index

# Replace in dataframe
application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(classification_types_to_replace, "Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [8]:
# You may find it helpful to look at CLASSIFICATION value counts >1
application_df['CLASSIFICATION'].value_counts()[application_df['CLASSIFICATION'].value_counts() > 1]

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [10]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classification_counts = application_df['CLASSIFICATION'].value_counts()
classifications_to_replace = classification_counts[classification_counts < 1000].index

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls, "Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [11]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df = pd.get_dummies(application_df, drop_first=True)

In [12]:
# Split our preprocessed data into our features and target arrays
X = application_df.drop("IS_SUCCESSFUL", axis=1)
y = application_df["IS_SUCCESSFUL"]

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [13]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [14]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
input_features = X_train_scaled.shape[1]
nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=80, activation='relu', input_dim=input_features))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=30, activation='relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 80)             │         2,960 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 30)             │         2,430 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            31 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 5,421 (21.18 KB)

 Trainable params: 5,421 (21.18 KB)

 Non-trainable params: 0 (0.00 B)

In [15]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [16]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7019 - loss: 0.5914
Epoch 2/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7282 - loss: 0.5590
Epoch 3/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7353 - loss: 0.5478
Epoch 4/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7345 - loss: 0.5463
Epoch 5/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7280 - loss: 0.5526
Epoch 6/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7257 - loss: 0.5514
Epoch 7/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7331 - loss: 0.5431
Epoch 8/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7330 - loss: 0.5437
Epoch 9/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7303 - loss: 0.5464
Epoch 10/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7319 - loss: 0.5477
Epoch 11/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7365 - loss: 0.5434
Epoch 12/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7338 - loss: 0.5457
Epoch 13/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7348 - loss: 0.5446
Epoch 14/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7306 - loss: 0.5501
Epoch 15/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7360 - loss: 0.5425
Epoch 16/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7325 - loss: 0.5482
Epoch 17/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7340 - loss: 0.5441
Epoch 18/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7338 - loss: 0.5455
Epoch 19/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7333 - loss: 0.5449
Epoch 20/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7399 - loss: 0.5401
Epoch 21/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7342 - loss: 0.5450
Epoch 22/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7370 - loss: 0.5430
Epoch 23/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7315 - loss: 0.5492
Epoch 24/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7378 - loss: 0.5418
Epoch 25/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7373 - loss: 0.5407
Epoch 26/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7349 - loss: 0.5471
Epoch 27/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7371 - loss: 0.5391
Epoch 28/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7399 - loss: 0.5381
Epoch 29/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7363 - loss: 0.5405
Epoch 30/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7409 - loss: 0.5363
Epoch 31/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7366 - loss: 0.5389
Epoch 32/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7392 - loss: 0.5391
Epoch 33/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7407 - loss: 0.5366
Epoch 34/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7384 - loss: 0.5417
Epoch 35/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7399 - loss: 0.5394
Epoch 36/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7333 - loss: 0.5434
Epoch 37/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7402 - loss: 0.5403
Epoch 38/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7371 - loss: 0.5413
Epoch 39/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.7352 - loss: 0.5419
Epoch 40/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7392 - loss: 0.5337
Epoch 41/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7376 - loss: 0.5402
Epoch 42/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7425 - loss: 0.5361
Epoch 43/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7376 - loss: 0.5380
Epoch 44/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7400 - loss: 0.5365
Epoch 45/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7383 - loss: 0.5403
Epoch 46/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7410 - loss: 0.5359
Epoch 47/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7338 - loss: 0.5410
Epoch 48/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7382 - loss: 0.5394
Epoch 49/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7375 - loss: 0.5402
Epoch 50/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7439 - loss: 0.5342
Epoch 51/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7380 - loss: 0.5370
Epoch 52/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7423 - loss: 0.5333
Epoch 53/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7413 - loss: 0.5336
Epoch 54/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7430 - loss: 0.5328
Epoch 55/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7411 - loss: 0.5326
Epoch 56/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7424 - loss: 0.5320
Epoch 57/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7416 - loss: 0.5334
Epoch 58/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7413 - loss: 0.5361
Epoch 59/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7371 - loss: 0.5400
Epoch 60/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7415 - loss: 0.5345
Epoch 61/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7454 - loss: 0.5319
Epoch 62/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.7418 - loss: 0.5314
Epoch 63/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7361 - loss: 0.5379
Epoch 64/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7428 - loss: 0.5311
Epoch 65/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.7409 - loss: 0.5384
Epoch 66/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.7385 - loss: 0.5354
Epoch 67/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7420 - loss: 0.5345
Epoch 68/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7421 - loss: 0.5357
Epoch 69/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7452 - loss: 0.5303
Epoch 70/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7442 - loss: 0.5312
Epoch 71/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7391 - loss: 0.5327
Epoch 72/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7388 - loss: 0.5331
Epoch 73/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7358 - loss: 0.5396
Epoch 74/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7428 - loss: 0.5319
Epoch 75/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.7361 - loss: 0.5378
Epoch 76/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.7428 - loss: 0.5305
Epoch 77/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7397 - loss: 0.5336
Epoch 78/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7385 - loss: 0.5367
Epoch 79/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7394 - loss: 0.5349
Epoch 80/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7350 - loss: 0.5400
Epoch 81/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7376 - loss: 0.5406
Epoch 82/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7395 - loss: 0.5362
Epoch 83/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7419 - loss: 0.5333
Epoch 84/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7439 - loss: 0.5279
Epoch 85/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7381 - loss: 0.5373
Epoch 86/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7430 - loss: 0.5317
Epoch 87/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7464 - loss: 0.5283
Epoch 88/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7418 - loss: 0.5317
Epoch 89/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7423 - loss: 0.5342
Epoch 90/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7397 - loss: 0.5315
Epoch 91/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7390 - loss: 0.5346
Epoch 92/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7391 - loss: 0.5328
Epoch 93/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7421 - loss: 0.5317
Epoch 94/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7437 - loss: 0.5306
Epoch 95/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7367 - loss: 0.5352
Epoch 96/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7406 - loss: 0.5334
Epoch 97/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7416 - loss: 0.5336
Epoch 98/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7361 - loss: 0.5337
Epoch 99/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7446 - loss: 0.5296
Epoch 100/100
751/751 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7396 - loss: 0.5333

In [17]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

322/322 - 1s - 2ms/step - accuracy: 0.7264 - loss: 0.5586
Loss: 0.5586090087890625, Accuracy: 0.7264334559440613

In [18]:
# Export our model to HDF5 file
nn.save("AlphabetSoupCharity.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.